version: '3.8'

services:
  backend:
    image: ${DOCKER_HUB_ID:-your-id}/${PROJECT_NAMESPACE:-quanty_trade}/quanty-backend:${APP_VERSION:-dev}
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/backend/data
    environment:
      - PORT=8080
      - DB_DRIVER=sqlite
    restart: always

  frontend:
    image: ${DOCKER_HUB_ID:-your-id}/${PROJECT_NAMESPACE:-quanty_trade}/quanty-frontend:${APP_VERSION:-dev}
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
