server:
  host: "0.0.0.0"
  port: 8080
  mode: "debug"

network:
  http_proxy: "http://127.0.0.1:1087"
  https_proxy: "http://127.0.0.1:1087"
  no_proxy: "127.0.0.1,localhost"

paths:
  logs_dir: "logs"
  strategies_dir: "strategies"

db:
  type: "mysql"
  host: "127.0.0.1"
  port: "3307"
  user: "quanty"
  pass: "quantypass"
  name: "quanty_trade"

admin:
  username: "admin"
  password: "admin123"

security:
  jwt_secret: "qt_jwt_secret_change_me_20260320"
  config_encryption_key: "b3e3c4f1a8d94b3a9c7f2e1d0a6b5c4d3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b8c"

exchange:
  name: "binance"
  binance:
    api_key: "2g60CgD0iZYf1ysqcI5HVXMvZKs7Pv5HnCzyrFMrEvH2NbAORjSwbTH4CQyjlRS9"
    api_secret: "OSFfTOgErRNRfY5mq17JN5VlQqc4w61CFcx6Y6BNDwVr6PD79SYdCPWlzrZy1yF4"
    testnet: false
    market: "usdm"
    base_url: "https://fapi.binance.com"
    ws_base_url: "wss://fstream.binance.com"
    wsapi_url: "wss://ws-api.binance.com:443/ws-api/v3"

redis:
  enabled: true
  addr: "137.220.219.172:6379"
  password: "work@..."
  db: 0
  prefix: "qt"
