package exchange

import (
	"strings"
	"time"
)

type Candle struct {
	// Timestamp is the candle open time (or close time depending on data source).
	Timestamp time.Time `json:"timestamp"`
	// Open is the candle open price.
	Open float64 `json:"open"`
	// High is the candle high price.
	High float64 `json:"high"`
	// Low is the candle low price.
	Low float64 `json:"low"`
	// Close is the candle close price.
	Close float64 `json:"close"`
	// Volume is the traded volume within the candle window.
	Volume float64 `json:"volume"`
}

type Order struct {
	// ID is the exchange order id (stringified).
	ID string `json:"id"`
	// ClientOrderID is the client-generated id used for correlation.
	ClientOrderID string `json:"client_order_id,omitempty"`
	// Symbol is the display symbol used by the platform (e.g. BTC/USDT).
	Symbol string `json:"symbol"`
	// Side is buy/sell.
	Side string `json:"side"` // "buy", "sell"
	// Amount is the order quantity in base asset.
	Amount float64 `json:"amount"`
	// Price is the order price (0 for market orders).
	Price float64 `json:"price"`
	// Status is the order lifecycle state (open/filled/canceled/...).
	Status string `json:"status"` // "open", "filled", "canceled"
	// Timestamp is the order time (exchange time if available).
	Timestamp time.Time `json:"timestamp"`
}

type Position struct {
	// Symbol is the display symbol (e.g. BTC/USDT).
	Symbol string `json:"symbol"`
	// Amount is the position size in base asset.
	Amount float64 `json:"amount"`
	// Price is the average entry price (platform-derived).
	Price float64 `json:"price"`
	// CurrentPrice is the latest mark/last price used for PnL display.
	CurrentPrice float64 `json:"current_price"`
	// UnrealizedPnL is the unrealized profit/loss for active positions.
	UnrealizedPnL float64 `json:"unrealized_pnl"`
	// ReturnRate is the unrealized return rate in percent (PnL / entry value * 100).
	ReturnRate float64 `json:"return_rate"`
	// ClosedQty is the cumulative closed quantity (history positions).
	ClosedQty float64 `json:"closed_qty,omitempty"`
	// AvgClosePrice is the VWAP close price (history positions).
	AvgClosePrice float64 `json:"avg_close_price,omitempty"`
	// RealizedPnL is the realized PnL (history positions).
	RealizedPnL float64 `json:"realized_pnl,omitempty"`
	// RealizedReturnRate is realized return rate in percent.
	RealizedReturnRate float64 `json:"realized_return_rate,omitempty"`
	// StrategyName is the strategy instance name that owns this position.
	StrategyName string `json:"strategy_name"`
	// ExchangeName is the exchange name (e.g. Binance).
	ExchangeName string `json:"exchange_name"`
	// Status is active/closed.
	Status string `json:"status"` // "active", "closed"
	// OwnerID is the user who owns this position.
	OwnerID uint `json:"owner_id"`
	// OpenTime is when position opened.
	OpenTime time.Time `json:"open_time"`
	// CloseTime is when position closed (if applicable).
	CloseTime time.Time `json:"close_time,omitempty"`
}

// Exchange is the abstraction used by Strategy Manager to access market data,
// place orders, and query positions.
//
// Conventions:
//   - symbol: uses platform display format (e.g. BTC/USDT). Implementations should
//     normalize to exchange-specific symbols internally.
//   - ownerID: determines which user's exchange credentials are used.
//   - clientOrderID: is generated by the platform to correlate order requests with
//     exchange execution reports.
type Exchange interface {
	// GetName returns a stable exchange identifier for UI and persistence (e.g. "Binance").
	GetName() string
	// FetchCandles returns the most recent candles for a symbol.
	// timeframe is exchange-specific (e.g. "1m", "1h"); limit is the number of bars.
	FetchCandles(symbol string, timeframe string, limit int) ([]Candle, error)
	// PlaceOrder sends an order to the exchange using the user's credentials.
	// price=0 means market order; non-zero means limit order (implementation-dependent).
	PlaceOrder(ownerID uint, clientOrderID string, symbol string, side string, amount float64, price float64) (*Order, error)
	// FetchOrders returns recent orders for a symbol for the user.
	FetchOrders(ownerID uint, symbol string) ([]Order, error)
	// FetchPositions returns current positions for a user.
	FetchPositions(ownerID uint, status string) ([]Position, error) // status: "active" or "closed"
	// SubscribeCandles pushes real-time candle updates to callback.
	// Implementations should handle reconnection internally where possible.
	SubscribeCandles(symbol string, callback func(Candle)) (func(), error)
	// ClosePosition closes a position for a user. Implementations may use market order.
	ClosePosition(symbol string, ownerID uint) error
	// FetchHistoricalCandles returns candles for backtesting within a time range.
	FetchHistoricalCandles(symbol string, timeframe string, startTime, endTime time.Time) ([]Candle, error)
}

// NormalizeSymbol converts a display symbol (e.g. BTC/USDT) into exchange format (e.g. BTCUSDT).
func NormalizeSymbol(symbol string) string {
	s := strings.ToUpper(symbol)
	s = strings.ReplaceAll(s, "/", "")
	s = strings.ReplaceAll(s, "-", "")
	return s
}

// MockExchange is a development-only exchange implementation.
// It does not connect to real markets and returns synthetic data.
type MockExchange struct {
	Name string
}

func (m *MockExchange) GetName() string { return m.Name }

func (m *MockExchange) FetchCandles(symbol string, timeframe string, limit int) ([]Candle, error) {
	// Mock implementation
	return []Candle{}, nil
}

func (m *MockExchange) PlaceOrder(ownerID uint, clientOrderID string, symbol string, side string, amount float64, price float64) (*Order, error) {
	return &Order{
		ID:            "mock-id",
		ClientOrderID: clientOrderID,
		Symbol:        symbol,
		Side:          side,
		Amount:        amount,
		Price:         price,
		Status:        "filled",
		Timestamp:     time.Now(),
	}, nil
}

func (m *MockExchange) FetchOrders(ownerID uint, symbol string) ([]Order, error) {
	return []Order{}, nil
}

func (m *MockExchange) FetchPositions(ownerID uint, status string) ([]Position, error) {
	if status == "active" {
		return []Position{
			{
				Symbol:       "BTC/USDT",
				Amount:       0.05,
				Price:        62000.0,
				StrategyName: "均线趋势策略",
				ExchangeName: m.Name,
				Status:       "active",
				OwnerID:      ownerID,
				OpenTime:     time.Now().Add(-2 * time.Hour),
			},
		}, nil
	} else {
		return []Position{
			{
				Symbol:       "ETH/USDT",
				Amount:       1.2,
				Price:        2450.0,
				StrategyName: "网格套利",
				ExchangeName: m.Name,
				Status:       "closed",
				OwnerID:      ownerID,
				OpenTime:     time.Now().Add(-24 * time.Hour),
				CloseTime:    time.Now().Add(-22 * time.Hour),
			},
		}, nil
	}
}

func (m *MockExchange) SubscribeCandles(symbol string, callback func(Candle)) (func(), error) {
	// Simulate data every 1 second
	stop := make(chan struct{})
	go func() {
		price := 60000.0
		for {
			select {
			case <-stop:
				return
			default:
			}
			price += float64((time.Now().UnixNano() % 100) - 50)
			callback(Candle{
				Timestamp: time.Now(),
				Open:      price,
				High:      price + 10,
				Low:       price - 10,
				Close:     price,
				Volume:    1.0,
			})
			time.Sleep(1 * time.Second)
		}
	}()
	return func() {
		select {
		case <-stop:
		default:
			close(stop)
		}
	}, nil
}

func (m *MockExchange) ClosePosition(symbol string, ownerID uint) error {
	// In mock, we just return success
	return nil
}

func (m *MockExchange) FetchHistoricalCandles(symbol string, timeframe string, startTime, endTime time.Time) ([]Candle, error) {
	// Generate some mock historical data
	var candles []Candle
	current := startTime
	price := 60000.0
	for current.Before(endTime) {
		price += float64((current.UnixNano() % 100) - 50)
		candles = append(candles, Candle{
			Timestamp: current,
			Open:      price,
			High:      price + 10,
			Low:       price - 10,
			Close:     price,
			Volume:    1.0,
		})
		current = current.Add(time.Hour)
	}
	return candles, nil
}
